# Generated by Django 5.1.1 on 2024-10-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_review_reviewentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewentry',
            name='image',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
